import { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

type View = "plan" | "setup" | "calibration" | "exercise" | "pause" | "result" | "check" | "progress" | "messages";
type Lang = "ru" | "kz" | "en";

const copy = {
  ru: { language: "Язык", greeting: "Добрый день", today: "План на сегодня", start: "Начать занятие", continue: "Продолжить", next: "Далее", calibrate: "Начать калибровку", pause: "Пауза", resume: "Продолжить занятие", finish: "Завершить", setup: "Подключите датчики", calibration: "Калибровка", exercise: "Текущее упражнение", result: "Занятие завершено", check: "Как вы себя чувствуете?", progress: "Прогресс", messages: "Сообщения", save: "Сохранить ответы", saved: "Спасибо, ответы сохранены в локальном demo.", plan: "План", synthetic: "Режим демонстрации · synthetic replay", notice: "Это synthetic replay для разработки. Данные не являются измерениями пациента и не используются для score, alert или клинических решений.", notCalculated: "Не рассчитано", waiting: "Ожидает", connected: "Готов", ready: "Датчики готовы", placement: "Разместите датчики как показано на схеме", stayStill: "Пожалуйста, сохраняйте неподвижность", calibrationDone: "Калибровка завершена", frames: "кадров replay", cue: "Выполняйте движение в комфортном темпе", before: "Боль до занятия", after: "Боль после занятия", difficulty: "Насколько сложным было занятие?", symptoms: "Новые симптомы", no: "Нет", yes: "Да", easy: "Легко", normal: "Нормально", hard: "Сложно", exerciseName: "Скольжение пяткой", duration: "~ 8 минут", reps: "10 повторений", pod: "день после операции", completed: "Выполнено занятий", adherence: "Выполнение плана", emptyMessages: "Новых сообщений пока нет", back: "К плану", stop: "Завершить занятие?", stopNote: "Вы сможете сообщить о самочувствии на следующем шаге.", confirmStop: "Да, завершить", cancel: "Вернуться к занятию" },
  kz: { language: "Тіл", greeting: "Қайырлы күн", today: "Бүгінгі жоспар", start: "Жаттығуды бастау", continue: "Жалғастыру", next: "Келесі", calibrate: "Калибрлеуді бастау", pause: "Кідірту", resume: "Жаттығуды жалғастыру", finish: "Аяқтау", setup: "Датчиктерді қосыңыз", calibration: "Калибрлеу", exercise: "Ағымдағы жаттығу", result: "Жаттығу аяқталды", check: "Өзіңізді қалай сезінесіз?", progress: "Прогресс", messages: "Хабарламалар", save: "Жауаптарды сақтау", saved: "Рақмет, жауаптар local demo ішінде сақталды.", plan: "Жоспар", synthetic: "Демо режимі · synthetic replay", notice: "Бұл әзірлеуге арналған synthetic replay. Деректер пациент өлшемі емес және score, alert не клиникалық шешімдерде қолданылмайды.", notCalculated: "Есептелмеді", waiting: "Күтуде", connected: "Дайын", ready: "Датчиктер дайын", placement: "Датчиктерді сызбада көрсетілгендей орналастырыңыз", stayStill: "Қозғалмай тұрыңыз", calibrationDone: "Калибрлеу аяқталды", frames: "replay кадры", cue: "Қозғалысты ыңғайлы қарқынмен орындаңыз", before: "Жаттығуға дейінгі ауырсыну", after: "Жаттығудан кейінгі ауырсыну", difficulty: "Жаттығу қаншалықты қиын болды?", symptoms: "Жаңа симптомдар", no: "Жоқ", yes: "Иә", easy: "Оңай", normal: "Қалыпты", hard: "Қиын", exerciseName: "Өкшені сырғыту", duration: "~ 8 минут", reps: "10 қайталау", pod: "операциядан кейінгі күн", completed: "Орындалған жаттығулар", adherence: "Жоспарды орындау", emptyMessages: "Әзірге жаңа хабарламалар жоқ", back: "Жоспарға", stop: "Жаттығуды аяқтау керек пе?", stopNote: "Келесі қадамда өзіңізді қалай сезінетініңізді хабарлай аласыз.", confirmStop: "Иә, аяқтау", cancel: "Жаттығуға оралу" },
  en: { language: "Language", greeting: "Good day", today: "Today’s plan", start: "Start session", continue: "Continue", next: "Next", calibrate: "Start calibration", pause: "Pause", resume: "Resume session", finish: "Finish", setup: "Connect your sensors", calibration: "Calibration", exercise: "Current exercise", result: "Session complete", check: "How are you feeling?", progress: "Progress", messages: "Messages", save: "Save answers", saved: "Thank you, responses are saved in this local demo.", plan: "Plan", synthetic: "Demo mode · synthetic replay", notice: "This is a synthetic replay for development. Data are not patient measurements and are not used for scoring, alerts, or clinical decisions.", notCalculated: "Not calculated", waiting: "Waiting", connected: "Ready", ready: "Sensors ready", placement: "Place the sensors as shown in the guide", stayStill: "Please stay still", calibrationDone: "Calibration complete", frames: "replay frames", cue: "Move at a comfortable pace", before: "Pain before session", after: "Pain after session", difficulty: "How difficult was the session?", symptoms: "New symptoms", no: "No", yes: "Yes", easy: "Easy", normal: "Normal", hard: "Hard", exerciseName: "Heel slide", duration: "~ 8 min", reps: "10 repetitions", pod: "day after surgery", completed: "Sessions completed", adherence: "Plan adherence", emptyMessages: "No new messages yet", back: "Back to plan", stop: "Finish this session?", stopNote: "You can tell us how you feel in the next step.", confirmStop: "Yes, finish", cancel: "Back to exercise" }
};

const Icon = ({ name, size = 20 }: { name: string; size?: number }) => {
  const paths: Record<string, string> = { home: "M3 10.5 12 3l9 7.5V21h-6v-6H9v6H3z", chart: "M4 20V10m5 10V4m5 16v-7m5 7V7", message: "M4 5h16v11H8l-4 4z", play: "m9 6 8 6-8 6z", pause: "M8 5v14m8-14v14", sensor: "M12 3a9 9 0 0 1 0 18M12 7a5 5 0 0 1 0 10M4 12h.01", check: "m5 12 4 4L19 6", arrow: "m9 18 6-6-6-6", close: "M6 6l12 12M18 6 6 18", heart: "M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.9-8.6a5.5 5.5 0 0 0-.1-7.8" };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]} /></svg>;
};

function App() {
  const [lang, setLang] = useState<Lang>("ru"); const [view, setView] = useState<View>("plan"); const [patient, setPatient] = useState("Пациент"); const [pod, setPod] = useState("—"); const [calibration, setCalibration] = useState(0); const [frames, setFrames] = useState(0); const [saved, setSaved] = useState(false); const [stopOpen, setStopOpen] = useState(false); const [painBefore, setPainBefore] = useState(0); const [painAfter, setPainAfter] = useState(0); const t = copy[lang];
  useEffect(() => { document.documentElement.lang = lang; }, [lang]);
  useEffect(() => { fetch("/api/v1/demo").then(r => r.json()).then(d => { setPatient(d.patient.display_name); setPod(String(d.patient.post_op_day)); }).catch(() => undefined); }, []);
  useEffect(() => { if (view !== "exercise" || stopOpen) return; const timer = window.setInterval(() => setFrames(value => value + 1), 680); return () => window.clearInterval(timer); }, [view, stopOpen]);
  useEffect(() => { if (view === "calibration" && calibration > 0 && calibration < 100) { const timer = window.setTimeout(() => setCalibration(value => Math.min(100, value + 25)), 480); return () => window.clearTimeout(timer); } }, [view, calibration]);
  const progress = useMemo(() => Math.min(100, Math.round((frames % 80) / 80 * 100)), [frames]);
  const sensorList = <div className="sensor-list">{["THIGH", "SHANK", "FOOT"].map((sensor, index) => <div className="sensor" key={sensor}><span className="sensor-icon"><Icon name="sensor" size={18} /></span><div><b>{sensor}</b><small>{index === 0 ? "Upper leg" : index === 1 ? "Lower leg" : "Foot"}</small></div><span className={`status ${view === "setup" && index ? "is-waiting" : ""}`}><i />{view === "setup" && index ? t.waiting : t.connected}</span></div>)}</div>;
  const metricCards = <div className="metric-grid">{[["ROM", t.notCalculated], ["Score", t.notCalculated], ["Signal", t.notCalculated]].map(([label, value]) => <div className="metric" key={label}><span>{label}</span><strong>—</strong><small>{value}</small></div>)}</div>;
  const go = (next: View) => { setStopOpen(false); setView(next); };
  let content: React.ReactNode;
  if (view === "plan") content = <><div className="eyebrow">{t.plan} · POD {pod}</div><h2>{t.today}</h2><p className="intro">{t.greeting}, <b>{patient}</b>. Выберите время, когда вам будет спокойно и удобно заниматься.</p><article className="exercise-card"><div className="exercise-art"><span className="leg leg-top" /><span className="leg leg-bottom" /><span className="exercise-dot" /></div><div className="exercise-info"><span className="tag">01</span><h3>{t.exerciseName}</h3><p>{t.duration} · {t.reps}</p><button className="primary" onClick={() => go("setup")}><Icon name="play" />{t.start}</button></div></article><div className="tip"><Icon name="heart" size={18} /><span>{t.cue}</span></div></>;
  else if (view === "setup") content = <><div className="step"><span>01</span><div><small>{t.setup}</small><b>{t.placement}</b></div></div><div className="placement"><div className="body-guide"><span className="head" /><span className="torso" /><span className="guide-leg one" /><span className="guide-leg two" /><i className="pin thigh">1</i><i className="pin shank">2</i><i className="pin foot">3</i></div><p>THIGH · SHANK · FOOT</p></div>{sensorList}<button className="primary full" onClick={() => go("calibration")}>{t.continue}<Icon name="arrow" /></button></>;
  else if (view === "calibration") content = <><div className="step"><span>02</span><div><small>{t.calibration}</small><b>{calibration === 100 ? t.calibrationDone : t.stayStill}</b></div></div><div className="calibration-orb"><div className={calibration ? "orb active" : "orb"}><Icon name={calibration === 100 ? "check" : "sensor"} size={48} /></div><strong>{calibration ? `${calibration}%` : "—"}</strong><p>{calibration === 100 ? t.ready : "Static technical check"}</p></div><div className="progress-line"><span style={{ width: `${calibration}%` }} /></div><button className="primary full" onClick={() => calibration === 100 ? go("exercise") : setCalibration(1)}>{calibration === 100 ? t.continue : t.calibrate}<Icon name="arrow" /></button></>;
  else if (view === "exercise") content = <><div className="session-top"><div><span className="live"><i /> LIVE REPLAY</span><h2>{t.exerciseName}</h2></div><button className="round" aria-label={t.pause} onClick={() => go("pause")}><Icon name="pause" /></button></div><div className="movement"><div className="motion-ring" style={{ "--progress": `${progress * 3.6}deg` } as React.CSSProperties}><div className="motion-inner"><span>{frames}</span><small>{t.frames}</small></div></div><p>{t.cue}</p></div>{sensorList}<div className="demo-cue"><span><Icon name="heart" size={17} /></span>{t.cue}</div><button className="secondary full" onClick={() => setStopOpen(true)}>{t.finish}</button>{stopOpen && <div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true"><button className="modal-close" aria-label="Close" onClick={() => setStopOpen(false)}><Icon name="close" /></button><h3>{t.stop}</h3><p>{t.stopNote}</p><button className="primary full" onClick={() => go("result")}>{t.confirmStop}</button><button className="text-button full" onClick={() => setStopOpen(false)}>{t.cancel}</button></div></div>}</>;
  else if (view === "pause") content = <><div className="pause-visual"><Icon name="pause" size={52} /></div><h2>{t.pause}</h2><p className="intro">Сделайте короткий перерыв. Когда будете готовы, вернитесь к движению.</p><button className="primary full" onClick={() => go("exercise")}><Icon name="play" />{t.resume}</button><button className="text-button full" onClick={() => go("result")}>{t.finish}</button></>;
  else if (view === "result") content = <><div className="success-mark"><Icon name="check" size={40} /></div><h2>{t.result}</h2><p className="intro">{t.exerciseName} · {frames} {t.frames}</p>{metricCards}<div className="demo-note"><b>{t.synthetic}</b><span>{t.notCalculated}</span></div><button className="primary full" onClick={() => go("check")}>{t.continue}<Icon name="arrow" /></button></>;
  else if (view === "check") content = <><div className="step"><span>03</span><div><small>{t.check}</small><b>Ваши ответы помогут врачу увидеть динамику</b></div></div><form onSubmit={event => { event.preventDefault(); setSaved(true); }}><div className="pain-row"><label>{t.before}<output>{painBefore}</output><input aria-label={t.before} type="range" min="0" max="10" value={painBefore} onChange={e => setPainBefore(Number(e.target.value))} /></label><label>{t.after}<output>{painAfter}</output><input aria-label={t.after} type="range" min="0" max="10" value={painAfter} onChange={e => setPainAfter(Number(e.target.value))} /></label></div><fieldset><legend>{t.difficulty}</legend><div className="choices">{[t.easy, t.normal, t.hard].map((value, i) => <label key={value}><input type="radio" required name="difficulty" value={i} defaultChecked={i === 1} /><span>{value}</span></label>)}</div></fieldset><fieldset><legend>{t.symptoms}</legend><div className="choices">{[t.no, t.yes].map((value, i) => <label key={value}><input type="radio" required name="symptoms" value={i} defaultChecked={!i} /><span>{value}</span></label>)}</div></fieldset><button className="primary full">{t.save}</button></form>{saved && <div role="status" className="saved"><Icon name="check" />{t.saved}<button onClick={() => go("plan")}>{t.back}</button></div>}</>;
  else if (view === "progress") content = <><div className="eyebrow">Последние 7 дней</div><h2>{t.progress}</h2><div className="progress-summary"><div><strong>3</strong><span>{t.completed}</span></div><div><strong>—</strong><span>ROM</span></div></div><section className="chart-card"><div className="chart-title"><b>{t.adherence}</b><span>Demo</span></div><div className="bars">{[38, 55, 42, 72, 61, 82, 67].map((height, i) => <i key={i} style={{ height: `${height}%` }} />)}</div><div className="week"><span>Пн</span><span>Вт</span><span>Ср</span><span>Чт</span><span>Пт</span><span>Сб</span><span>Вс</span></div></section><p className="footnote">{t.notice}</p></>;
  else content = <><div className="eyebrow">PHOENIX CARE</div><h2>{t.messages}</h2><div className="empty"><span><Icon name="message" size={30} /></span><b>{t.emptyMessages}</b><p>Здесь будут отображаться сообщения вашей команды восстановления.</p></div></>;
  return <div className="app-shell"><header className="topbar"><a className="brand" href="#plan" onClick={() => go("plan")}><span>p</span>PHOENIX</a><label className="language"><span>{t.language}</span><select value={lang} onChange={e => setLang(e.target.value as Lang)} aria-label={t.language}><option value="ru">РУ</option><option value="kz">ҚЗ</option><option value="en">EN</option></select></label></header><main><div className="replay-notice"><i /><span>{t.synthetic}</span><button aria-label="Information" title={t.notice}>i</button></div><section className="content" aria-live="polite">{content}</section></main><nav className="bottom-nav"><button className={view === "plan" ? "active" : ""} onClick={() => go("plan")}><Icon name="home" /><span>{t.plan}</span></button><button className={view === "progress" ? "active" : ""} onClick={() => go("progress")}><Icon name="chart" /><span>{t.progress}</span></button><button className={view === "messages" ? "active" : ""} onClick={() => go("messages")}><Icon name="message" /><span>{t.messages}</span></button></nav></div>;
}
createRoot(document.getElementById("root")!).render(<App />);
