-- Stage 5: the first exercise library. All definitions remain draft until
-- clinical review supplies approved instructions, thresholds and formulas.
INSERT INTO exercise_definitions (id, organization_id, name, definition_version, configuration)
VALUES
('exercise-short-arc-quad-v1', 'org-demo', 'Short Arc Quad', 1, '{"recovery_phase":null,"patient_position":null,"required_sensors":["thigh","shank","foot"],"reference_video":null,"instructions":{},"primary_metrics":[],"secondary_metrics":[],"prescription_schema":["sets","repetitions","frequency","target_rom_degrees","tempo","hold_seconds"],"valid_repetition_definition":null,"stop_conditions":[],"live_feedback_whitelist":[],"scoring_formula":null,"limitations":["Draft; clinical configuration required."],"approval_state":"draft"}'::jsonb),
('exercise-ankle-pumps-v1', 'org-demo', 'Ankle Pumps', 1, '{"recovery_phase":null,"patient_position":null,"required_sensors":["thigh","shank","foot"],"reference_video":null,"instructions":{},"primary_metrics":[],"secondary_metrics":[],"prescription_schema":["sets","repetitions","frequency","target_rom_degrees","tempo","hold_seconds"],"valid_repetition_definition":null,"stop_conditions":[],"live_feedback_whitelist":[],"scoring_formula":null,"limitations":["Draft; clinical configuration required."],"approval_state":"draft"}'::jsonb),
('exercise-straight-leg-raise-v1', 'org-demo', 'Straight Leg Raise', 1, '{"recovery_phase":null,"patient_position":null,"required_sensors":["thigh","shank","foot"],"reference_video":null,"instructions":{},"primary_metrics":[],"secondary_metrics":[],"prescription_schema":["sets","repetitions","frequency","target_rom_degrees","tempo","hold_seconds"],"valid_repetition_definition":null,"stop_conditions":[],"live_feedback_whitelist":[],"scoring_formula":null,"limitations":["Draft; clinical configuration required."],"approval_state":"draft"}'::jsonb),
('exercise-prone-knee-bend-v1', 'org-demo', 'Prone Knee Bend', 1, '{"recovery_phase":null,"patient_position":null,"required_sensors":["thigh","shank","foot"],"reference_video":null,"instructions":{},"primary_metrics":[],"secondary_metrics":[],"prescription_schema":["sets","repetitions","frequency","target_rom_degrees","tempo","hold_seconds"],"valid_repetition_definition":null,"stop_conditions":[],"live_feedback_whitelist":[],"scoring_formula":null,"limitations":["Draft; clinical configuration required."],"approval_state":"draft"}'::jsonb)
ON CONFLICT (id) DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_exercise_definitions_catalog
    ON exercise_definitions (organization_id, name, definition_version DESC);
